### ISSUE TITLE
WP Admin as a User Experience by Jamie Sanchez on 10/19/2016

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#51]
WP Admin as a User Experience

Leave those divs out of the WYSIWYG. Clean up that editing screen. This session covers the basics of Advanced Custom Fields, modifying the admin menu, and other ways to dummy-proof wp-admin and simplify data entry.

**Comment by cy-by** [comment]
In archive, no link to slides.
