### ISSUE TITLE
Jekyll - Static Sites on Steroids by Colt Borg on 01/11/2017

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#52]
[Jekyll - Static Sites on Steroids](https://paper.dropbox.com/doc/Jekyll-Workshop-VMbJfS3a8IzRJQaOeq8eu)

Do you want a blog but don't want to host WordPress or the like? Ditch the database and host your blog on GitHub for free. We'll cover how to install Jekyll, use its command line tools, how to add dynamic content with liquid, and finally to deploy to GitHub. By the end, you'll have a website ready for you to blog until your heart's content!

**Comment by cy-by** [comment]
Link in archive.
