### ISSUE TITLE
Inclusivity in Video Games + Nintendo Celebration by Paul Bersch on 02/28/2017

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#53]
[Inclusivity in Video Games + Nintendo Celebration](https://gitpitch.com/paulbersch/vg-presentation/master?grs=github&t=black)

The spirit of Nintendo is one of creativity and inclusivity, inspiring a generation of games that can be played by anyone and that are more representative and diverse. I'll explore the ways indie, mobile, and mainstream games are becoming more inclusive, the missteps Nintendo and other developers have made, and how gaming is a hobby for everyone (especially people who don't identify as "gamers"). Then we'll play Wii U and 3DS (Pokemon!) games together!

**Comment by cy-by** [comment]
Link in archive.
