### ISSUE TITLE
Career Iteration: A Design Celebration by Chris Wilkinson on 06/21/2017

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#55]
Career Iteration: A Design Celebration

"Assumptions: Design is a moving target, chasing the future, embracing the now, and delivering meaningful experiences and value to businesses and users.

Assertion: The most meaningful realization of design does not have to happen in the Obvious places, and you might be overlooking potential for great design. 

Let's explore where design happens, and what makes design Design."

**Comment by cy-by** [comment]
In archive, no link to slides.
