### ISSUE TITLE
Intentional and Accidental Career Development by David Michaels on 09/19/2017

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#58]
Intentional and Accidental Career Development

From 2014 to 2017 I grew from being the office IT person to a devops engineer. Sometimes I was given great opportunities, sometimes I had to fight to learn or move throughout the company. I was given lots of help sometimes and dutifully ignored at others. In the end, I'm in a wholly different career than I expected to be.

**Comment by cy-by** [comment]
In archive, no link to slide.
