### ISSUE TITLE
Color Choreography of/a/an Pop Music Video: Presenting Considerate Epistemology and Culture by Julia Murray on 10/24/2017

### ISSUE THREAD

**Issue by brianmontanaweb** [Vwampage/friends-irl#59]
[Color Choreography of/a/an Pop Music Video: Presenting Considerate Epistemology and Culture](https://readymag.com/u67292053/889883/)

We're going to drink and watch 90s music videos and I'm going to say some words.

**Comment by cy-by** [comment]
Link in archive.
