### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by cy-by** [Vwampage/friends-irl#70]
This discuss came from #68 and weren't addressed. I've created this issue to discuss the point and complete the required work.

If we plan to continue adding talks, do you think it'd be worth writing a script that generates the /archive page from a .json file or something?
* This is being discussed in #69.

The favicon is not showing up on either of the pages on my machine and I can't find a reference to the `.ico` in any of the files in either repo, I might be missing something but I'm not sure how it's showing up in prod.
* Since this have been merged to prod, I'm seeing the favicon working probably on my end. the `.ico` is in the main directory.

Should we make the spacing around the line break between the "Talk Archive" header and list of talks even?
* @beckyrother suggested that the subheader be widened so that it only take one line. If this is the consensus, that could be easily implemented.

nit ~ I think there's an extra comma after David's name :P
* Good catch! `DevOps` needs to be added after David's name :)

Clicking on the icon in the top should take the user back to the home page; can the buttons at the top stay the same between each page?
* Shouldn't be a problem to implement.

Add a home button under the subhead
@beckyrother where exactly should this be?

Subhead copy to come :)
@beckyrother you can add any copy on this issue!

**Comment by beckyrother** [comment]
Thanks for starting this @coltborg ! 

- can the header image just be the Home button? I've clicked it a few times expecting it to be a link, ha
- what other subhead copy? I'm hesitant to try to write for a specific page with since this is responsive

**Comment by cy-by** [comment]
This issue was completed!
